MainView/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout


app_name = 'MainView'
urlpatterns = [
    url(r'', views.IndexView.as_view(), name='main_view_index'),  
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RTsite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, include
from django.apps import apps
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout

"""
    Check data for uploading
"""
from django.conf import settings 
from django.conf.urls.static import static 

app_name = 'RTsite'
admin.site.site_header = "RTMK Admin"
admin.site.site_title = "RTMK Admin Portal"
admin.site.index_title = "Welcome to RTMK product marketing "

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^admin/', include(admin.site.urls)),
    # path('category/', include('category.urls')),
    # path('', include('category.urls')), # login at the page loading. http://127.0.0.1:8000 #


    # path('product/', include('product.urls')),
    path('product_history/', include('product_history.urls')),
    path('usercontrol/', include('usercontrol.urls')),
    path('MainView/', include('MainView.urls')),
    path('customer/', include('customer.urls')),
    path('sell/', include('sell.urls')),
    path('', include('product.urls')),


    # path(
    #     'admin/password_reset/',
    #     auth_views.PasswordResetView.as_view(),
    #     name='admin_password_reset',
    # ),
    # path(
    #     'admin/password_reset/done/',
    #     auth_views.PasswordResetDoneView.as_view(),
    #     name='password_reset_done',
    # ),
    # path(
    #     'reset/<uidb64>/<token>/',
    #     auth_views.PasswordResetConfirmView.as_view(),
    #     name='password_reset_confirm',
    # ),
    # path(
    #     'reset/done/',
    #     auth_views.PasswordResetCompleteView.as_view(),
    #     name='password_reset_complete',
    # ),
    
    # url(r'^admin/', admin.site.urls),
    # url(r'^category/', views.index, 'category-index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout

app_name = 'customer'

urlpatterns = [
    path('', views.IndexView.as_view(), name='customer_index'),
    url(r'^detail/(?P<full_name>[0-9, a-z, A-Z]+)/$', views.CustomerDetailView.as_view(), name='customer_detail'),
    url(r'^export_customer_invoice/(?P<full_name>[0-9, a-z, A-Z]+)/$', views.ExportCustomerInvoiceView.as_view(), name='export_customer_invoice'),
    url(r'^search_customer_invoice/$', views.SearchCustomerInvoice.as_view(), name='search_customer_invoice'),
    url(r'^export_search_customer_invoice/(?P<full_name>[0-9, a-z, A-Z]+)/(?P<start_date>[0-9, a-z, A-Z]+)/(?P<end_date>[0-9, a-z, A-Z]+)/$', views.ExportSearchCustomerInvoice.as_view(), name='export_search_customer_invoice'),

    url(r'^list_invoice_detail/(?P<invoice_no>[0-9, a-z, A-Z]+)/$', views.ListInvoiceDetailView.as_view(), name='list_invoice_detail'),
    url(r'^list_client/$', views.ListClient.as_view(), name='list_client'),
    url(r'^owe_list/$', views.OweClient.as_view(), name='owe_list'),
    url(r'^compansate_remaining/(?P<invoice_no>[0-9, a-z, A-Z]+)/$', views.CompansateRemaining.as_view(), name='compansate_remaining'),
    url(r'^make_payment/$', views.MakePayment.as_view(), name='make_payment'),
    url(r'^owe_list_search/$', views.OweListSearch.as_view(), name='owe_list_search'),
    url(r'^save_list/$', views.SaveList.as_view(), name='save_list'),
    url(r'^delete_save/(?P<pk>[0-9]+)/$', views.DeleteSave.as_view(), name='delete_save'),
    url(r'^search_save_list/$', views.SearchSaveList.as_view(), name='search_save_list'),
    url(r'^save_payment/(?P<invoice_no>[0-9, a-z, A-Z]+)/$', views.PaymentSaveView.as_view(), name='save_payment'),
    url(r'^make_save_payment/$', views.MakeSavePayment.as_view(), name='make_save_payment'),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout


from .views import SearchProductView, RateView

app_name = 'product'

urlpatterns = [
    path('', views.IndexView.as_view(), name='product_index'),
    path('search/', SearchProductView.as_view(), name='product_search'),
    path('request_rate/', RateView.as_view(), name='request_rate'),
    # path('request_rate/', views.RateView, name='request_rate'),
  
  	url(r'^product_in_stock/', views.ProductInStockView.as_view(), name='product_in_stock'),
    url(r'^detail/(?P<pk>[0-9]+)/', views.DetailView.as_view(), name='product_detail'),
    url(r'^category_list/', views.CategoryListView.as_view(), name='category_list'),
    url(r'^category_product/(?P<pk>[0-9]+)/(?P<cate_name>[0-9, a-z, A-Z]+)/', views.CategoryProductView.as_view(), name='category_product'),
    url(r'^export_stock/$', views.ExportStock.as_view(), name='export_stock'),
    
    # url(r'^$', views.IndexView.as_view(), name='product_index'),
 
    # url(r'^request_rate/$', views.RateView.as_view(), name='request_rate'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sell/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout


app_name = 'sell'
urlpatterns = [
    url(r'^$', views.SaleView.as_view(), name='sale_view'),
   	url(r'^filter_category/$', views.filter_category, name='filter_category'),
   	url(r'^filter_product/$', views.filter_product, name='filter_product'),
   	url(r'^filter_customer/$', views.filter_customer, name='filter_customer'),
   	url(r'^save_order_product_list/$', views.save_order_product_list, name='save_order_product_list'),
   	url(r'^check_invoice_product_list/$', views.check_invoice_product_list, name='check_invoice_product_list'),
   	url(r'^make_invoice_payment/$', views.make_invoice_payment, name='cancelSelling'),
   	url(r'^cancel_selling/$', views.cancel_selling, name='cancel_selling'),
    url(r'^update_order/$', views.update_order, name='update_order'),
    url(r'^delete_invoice/$', views.delete_invoice, name='delete_invoice'),
    url(r'^sub_make_invoice_payment/$', views.sub_make_invoice_payment, name='sub_make_invoice_payment'),
    url(r'^sub_make_payment/$', views.sub_make_payment, name='sub_make_payment'),
    url(r'^print_report/(?P<invoice_id>[0-9, a-z, A-Z]+)/$', views.print_report.as_view(), name='print_report'),
    url(r'^sell_history/$', views.SellHistoryView.as_view(), name='sell_history'),

   
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainView/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from datetime import date
from django.conf import settings
import os
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from location.models import Location

# from tinymce.models import HTMLField

# Create your models here.

def upload_location(instance, filename):
		filebase, extension = filename.split(".")
		return "%s/%s.%s" %(instance.id, instance.id, extension)

def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.png', '.jpg', '.jpeg']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Unsupported file extension.')



def user_directory_path(request, filename):
	# return "files/users/%s/%s" % (request.user.id, filename)
    return '/'.join(['content', request.name, filename])

class ProductCategory(models.Model):
    name = models.CharField(max_length=255)
    icon = models.FileField(blank=True, upload_to=user_directory_path,  validators=[validate_file_extension])
    description = models.TextField() 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    is_status = models.BooleanField(default=True)
    def __str__ (self):
    	# return self.name + ' ' + str(self.created_at)
    	return self.name 
    class  Meta:
    	ordering = ['-created_at']

def increment_product_number():
	last_product = Product.objects.all().order_by('id').last()
	if not last_product:
		return 'RTMK00001'
	width = 5
	product_number = last_product.product_number
	product_int = int(product_number.split('RTMK')[-1])
	new_product_int = product_int + 1
	formatted = (width - len(str(new_product_int))) * "0" + str(new_product_int)
	new_product_int = 'RTMK' + str(formatted)
	return str(new_product_int)

class ProductType(models.Model):
	title = models.CharField(max_length=20)
	amount = models.IntegerField(default=0) # Amount of product in one type (Eg. 1 box = 10)
	description = models.TextField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	is_status = models.BooleanField(default=True)

	def __str__(self):
		return self.title
	class Meta:
		ordering = ['-created_at']
		
		def __unicode__(self):
			return str(self.title)

class Product(models.Model):
	product_category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE) # Box, Bottle ...etc
	product_number = models.CharField(max_length=500, null=True, blank=True, 
        validators=[RegexValidator(regex='^[a-zA-Z0-9]*$',
        message='Produce number must be Alphanumeric',code='Number is invalide'),], 
        default=increment_product_number)
	serial_number = models.CharField(max_length=150, default=0, null=True, blank=True)
	default_image = models.FileField(upload_to=user_directory_path,  validators=[validate_file_extension])
	size = models.CharField(max_length=250, default="", null=True, blank=True)
	color = models.CharField(max_length=20, default="", null=True, blank=True)
	price =  models.FloatField(default=0.0) # Price for each product item in per/unit
	special_price = models.FloatField(default=0.0) # In case some clients buy many products
	description = models.TextField()
	review = models.IntegerField(default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	is_status = models.BooleanField(default=True)

	# def get_absolute_url(self):
	# 		return reverse('product:detail', kwargs={'pk':self.pk})

	def __str__ (self):
		return self.name

	class Meta:
	    ordering = ['-created_at']
	    def __unicode__(self):
	        return self.name

class Rate(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	rate_number = models.FloatField(default=0.0)
	rate = models.FloatField(default=0.0)
	is_status = models.BooleanField(default=True)
	
class SubProductImage(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	name = models.CharField(max_length = 150)
	sub_image = models.FileField(blank=True, upload_to=user_directory_path,  validators=[validate_file_extension])
	description = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	is_status = models.BooleanField(default=True)

	def __str__ (self):
		return self.name

	class Meta:
	    ordering = ['-created_at']
	    def __unicode__(self):
	    	return self.name

class StockLocation(models.Model):
	name = models.CharField(max_length=255)
	location = models.ForeignKey(Location, on_delete=models.CASCADE)
	address = models.TextField()
	controller = models.ForeignKey(User, on_delete=models.CASCADE)
	email = models.EmailField(max_length=250)
	phone_number = models.CharField(max_length=150)
	description = models.TextField(blank=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	is_status = models.BooleanField(default=True)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['-created_at']
		def __unicode__(self):
			return self.name
			
class ProductInStock(models.Model):
	product = models.ForeignKey(Product, related_name='product_in_stock', on_delete=models.CASCADE)
	title = models.CharField(max_length=150, null=True, blank=True)
	# unit_title = models.CharField(max_length=50, blank=True) # Bottle, Tube, Box 
	unit = models.IntegerField(default=0) # Amount of Unit
	amount =  models.IntegerField(default=0) # Amount product of product in stock per Unit
	# stock_location = models.ForeignKey(StockLocation, on_delete=models.CASCADE)
	description = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	is_status = models.BooleanField(default=True)

	def __str__ (self):
		return self.title
	class Meta:
	    ordering = ['-created_at']
	    def __unicode__(self):
	        return self.title

class Promotion(models.Model):
	title = models.CharField(max_length=200, null=True, blank=None)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	discount_as_percentag = models.IntegerField(default=0) 
	discount_as_price = models.FloatField(default=0.0) 
	promotion_image = models.FileField(blank=True, upload_to=user_directory_path,  validators=[validate_file_extension])
	description = models.TextField()
	start_date = models.DateTimeField(auto_now=False, auto_now_add=False)
	end_date = models.DateTimeField(auto_now=False, auto_now_add=False)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	is_status = models.BooleanField(default=True)

	def __str__ (self):
		return self.title
	class Meta:
	    ordering = ['-created_at']
	    def __unicode__(self):
	        return self.title

class ProductUnit(models.Model):
	title = models.CharField(max_length=255)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	unit = models.CharField(max_length=255)
	description = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	is_status = models.BooleanField(default=True)

	def __str__ (self):
		return self.title

	class Meta:
	    ordering = ['-created_at']
	    def __unicode__(self):
	        return self.title

class ProductInStockHistory(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	title = models.CharField(max_length=150, null=True, blank=True)
	# unit_title = models.CharField(max_length=250) # Bottle, Tube, Box 
	unit = models.IntegerField(default=0) # Amount of Unit
	amount =  models.IntegerField(default=0) # Amount product of product in stock per Unit
	description = models.TextField()
	action = models.CharField(max_length=20, null=True, blank=True) # NO SVE, UPD, DEL
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	is_status = models.BooleanField(default=True)

	def __str__ (self):
		return self.title

	class Meta:
	    ordering = ['-created_at']
	    def __unicode__(self):
	        return self.title

# All products will store in producthistory table
# Including adding new products, update product 
class ProductHistory(models.Model):
	product_category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	product_number = models.CharField(max_length=500, null=True, blank=True, 
        validators=[RegexValidator(regex='^[a-zA-Z0-9]*$',
        message='Produce number must be Alphanumeric',code='Number is invalide'),], 
        default=increment_product_number)
	serial_number = models.CharField(max_length=150, default=0, null=True, blank=True)
	default_image = models.FileField(blank=True, upload_to=user_directory_path,  validators=[validate_file_extension])
	size = models.CharField(max_length=250, null=True, blank=True)
	color = models.CharField(max_length=20, null=True, blank=True)
	price =  models.FloatField(default=0.0) # Price for each product item in per/unit
	special_price = models.FloatField(default=0.0) # In case some clients buy many products
	description = models.TextField()
	review = models.IntegerField(default=0)
	action = models.CharField(default="", max_length=10) # save, update, delete
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now_add=True)
	is_status = models.BooleanField(default=True)

	def get_absolute_url(self):
			return reverse('product:detail', kwargs={'pk':self.pk})

	def __str__ (self):
		return self.name

	class Meta:
	    ordering = ['-created_at']
	    def __unicode__(self):
	        return self.name

MainView/templates/product/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
	
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Latest compiled and minified CSS -->
	<!-- /<script  type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"> </script> -->
    <!-- <script src="//code.jquery.com/jquery-1.11.1.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
   
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

	<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.js' %}" charset="UTF-8"></script>
	<script type="text/javascript" src="{% static 'js/locales/bootstrap-datetimepicker.en.js' %}" charset="UTF-8"></script>
	<script type="text/javascript" src="{% static 'js/rate.js' %}" charset="UTF-8"></script>
	<link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
	<script  type="text/javascript" src="{% static 'js/rate.js' %}"> </script>
	<script  type="text/javascript" src="{% static 'js/slidebar.js' %}"> </script>

	<link rel="stylesheet"  href="{% static 'css/main.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/style.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/krotis.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/pralis.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/login.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/product.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/rate.css' %}"/>
	<link rel="stylesheet"  href="{% static 'css/slidebar.css' %}">
	<link rel="stylesheet"  href="{% static 'css/homepage.css' %}">
	<link rel="stylesheet"  href="{% static 'css/stock.css' %}">
	<link rel="stylesheet"  href="{% static 'css/user.css' %}">
	<link rel="stylesheet"  href="{% static 'css/category.css' %}">
	<link rel="stylesheet"  href="{% static 'css/sell.css' %}">
	<link rel="stylesheet"  href="{% static 'css/client.css' %}">
	
    <title>{% block title %}{% endblock %}</title>

    {% block stylesheet %}
		
    {% endblock %}

</head>
<body>
	{% block loader %}

	{% endblock %}
	<div>
		<header class="bs-docs-nav navbar navbar-static-top my_header" id="top"> 
			<div class="container"> 
				<div class="navbar-header"> 
					<button aria-controls="bs-navbar" aria-expanded="false" class="collapsed navbar-toggle" data-target="#bs-navbar" data-toggle="collapse" type="button"> 
						<span class="sr-only">Toggle navigation</span> 
						<span class="icon-bar"></span> 
						<span class="icon-bar"></span> 
						<span class="icon-bar"></span> 
					</button> 
					
				
					{% if user.is_authenticated %}
						<div id="mySidenav" class="sidenav">
						    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
						    <a href="{% url 'MainView:main_view_index' %}"><span class="glyphicon glyphicon-th-large"></span>  Dashboard</a> <!-- Stock --> 
						    <hr style="margin-bottom: 0px !important; "> 
						    <a href="{% url 'product:product_in_stock' %}"><span class="glyphicon glyphicon-book"></span>  Stock</a> <!-- Stock --> 
						    <hr style="margin-bottom: 0px !important; "> 
						    <a href="{% url 'product:product_index' %}"><span class="glyphicon glyphicon-list-alt"></span>  Product</a>
						    <hr style="margin-bottom: 0px !important; ">
						    <a href="{% url 'sell:sale_view' %}"><span class="glyphicon glyphicon-shopping-cart"></span>  Sale</a> <!-- Sale -->
						    <hr style="margin-bottom: 0px !important; ">
						    <a href="{% url 'customer:owe_list' %}"><span class="glyphicon glyphicon-list-alt"></span>  Owe</a> <!-- Owe -->
						    <hr style="margin-bottom: 0px !important; ">
						    <a href="{% url 'customer:save_list' %}"> <span class="glyphicon glyphicon-hdd"></span>  Save list </a>
						    <hr style="margin-bottom: 0px !important; ">
						    <a href="{% url 'usercontrol:all_user_invoice' %}"> <span class="glyphicon glyphicon-print"></span>  Report list </a>
						    <hr style="margin-bottom: 0px !important; ">
						    {% if request.user.is_superuser %}
							    <a href="{% url 'sell:sell_history' %}"> <span class="glyphicon glyphicon-tasks"></span>  History </a>
							    <hr style="margin-bottom: 0px !important; ">
						    {% endif %}
						</div>


					    <div class="navbar-brand">
		                    <span style="font-size:30px;cursor:pointer" onclick="openNav()">☰</span>
		                </div>
		            {% else %}
		            	
		                <a class="navbar-brand" href="{% url 'product:product_index' %}"> KRT Marketing </a>
		                
		            {% endif %}
					            
					
				</div> 

				
				<nav class="collapse navbar-collapse" id="bs-navbar">
			
					{% if user.is_authenticated %}
						<ul class="nav navbar-nav navbar-right">

							{% if user.profile.is_recruit == "1" %}
								<li class="">
									<a href="#">
										<span class="glyphicon glyphicon-bullhorn" aria-hidden=true> Recruitment </span>
									</a>
								</li>
								
							{% endif %}
							<li class="">
								<a href="#">
									<span class="glyphicon glyphicon glyphicon-user" aria-hidden=true> {{ user.username }} </span>
								</a>
							</li>
							<li class="">
								<a href="{% url 'usercontrol:auth_logout' %}">
									<span class="glyphicon glyphicon-off" aria-hidden=true> Logout </span>
								</a>
							</li>
						</ul>

					{% else %}
					    
					    <ul class="nav navbar-nav navbar-right">
							
							<li class="">
								<a href="{% url 'usercontrol:login' %}">
									<span class="glyphicon glyphicon-user" aria-hidden=true> Login </span>
								</a>
							</li>
							<!-- <li class="">
								<a href="#">
									<span class="glyphicon glyphicon-registration-mark" aria-hidden=true> Register </span>
								</a>
							</li> -->
						</ul>
					{% endif %}	
					</ul> 
				</nav> 
			</div> 
		</header>

	<main class="bd-content p-5" id="content" role="main">
		
		<div class="container bs-docs-container" style="min-height: 500px; ">
			{% block body %}

			{% endblock %}
		</div>

	</main>

	<footer>
			<div class="bs-docs-footer">
				<div class="container">
					<div class="row">
						<div class="col-md-4" style="text-align: center;">
							<h4>Follow Us: </h4>
						    {% if all_media %}
						    	<ul class="bs-docs-footer-links">
									{% for i in all_media %}
										<li>
											<a href="{{ i.url }}" target="_blank">
												<img src = "../../../{{ i.logo.url }}" style="width: 40px; height: 40px;">
											</a>
										</li>
									{% endfor %}
								</ul>

							{% endif %}
						</div>
						<div class="col-md-4" style="text-align: center;">
							<h4>Contact Us:</h4>
							<p><span class="glyphicon glyphicon-envelope"> </span> Email: Setec.rithy@gmail.com</p>
							<p><span class="glyphicon glyphicon-earphone"></span> Tel: (+855)98-524-777</p>
							
						</div>
						<div class="col-md-4" style="text-align: center; !important;">
							<h4>Address: </h4>
							<span style="">VengSreng Street, BE7 House, PreyLvea Village, ChomChao Commune, PorSenChey District, Phnom Penh City.</span>
						</div>
					</div>
				</div>
			</div>



			<div style="width: 100%; min-height: 50px; height: auto; background-color: #252525;">
				<div class="container">
					<div class="row" style="padding-top: 20px;">
						<div class="col-md-12" style="text-align: center; color:white;">
							<p>Copyright ©2019 Ai Cambodia. Tel: (+855)93-524-860, Email: nginkimlong@gmail.com</p>
						</div>
					</div>
				</div>
			</div>
		</footer>

	{% block javascript %}
		
	{% endblock %}
</div>
</body>
</html>

MainView/templates/product/list_client.html
{% extends 'product/base.html' %}

{% block title %} Product {% endblock %}

{% block body %}

	<div class="index_background">
			<div class="head_index">
			
				<div class="home_title">
					<p> <span class="glyphicon glyphicon-list-alt">  </span>   list </p>
				</div>

			</div>
	</div>
{% endblock %}