MainView/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout


app_name = 'MainView'
urlpatterns = [
    url(r'', views.IndexView.as_view(), name='main_view_index'),  
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RTsite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, include
from django.apps import apps
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout

"""
    Check data for uploading
"""
from django.conf import settings 
from django.conf.urls.static import static 

app_name = 'RTsite'
admin.site.site_header = "RTMK Admin"
admin.site.site_title = "RTMK Admin Portal"
admin.site.index_title = "Welcome to RTMK product marketing "

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^admin/', include(admin.site.urls)),
    # path('category/', include('category.urls')),
    # path('', include('category.urls')), # login at the page loading. http://127.0.0.1:8000 #


    # path('product/', include('product.urls')),
    path('product_history/', include('product_history.urls')),
    path('usercontrol/', include('usercontrol.urls')),
    path('MainView/', include('MainView.urls')),
    path('customer/', include('customer.urls')),
    path('sell/', include('sell.urls')),
    path('', include('product.urls')),


    # path(
    #     'admin/password_reset/',
    #     auth_views.PasswordResetView.as_view(),
    #     name='admin_password_reset',
    # ),
    # path(
    #     'admin/password_reset/done/',
    #     auth_views.PasswordResetDoneView.as_view(),
    #     name='password_reset_done',
    # ),
    # path(
    #     'reset/<uidb64>/<token>/',
    #     auth_views.PasswordResetConfirmView.as_view(),
    #     name='password_reset_confirm',
    # ),
    # path(
    #     'reset/done/',
    #     auth_views.PasswordResetCompleteView.as_view(),
    #     name='password_reset_complete',
    # ),
    
    # url(r'^admin/', admin.site.urls),
    # url(r'^category/', views.index, 'category-index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout

app_name = 'customer'

urlpatterns = [
    path('', views.IndexView.as_view(), name='customer_index'),
    url(r'^detail/(?P<full_name>[0-9, a-z, A-Z]+)/$', views.CustomerDetailView.as_view(), name='customer_detail'),
    url(r'^export_customer_invoice/(?P<full_name>[0-9, a-z, A-Z]+)/$', views.ExportCustomerInvoiceView.as_view(), name='export_customer_invoice'),
    url(r'^search_customer_invoice/$', views.SearchCustomerInvoice.as_view(), name='search_customer_invoice'),
    url(r'^export_search_customer_invoice/(?P<full_name>[0-9, a-z, A-Z]+)/(?P<start_date>[0-9, a-z, A-Z]+)/(?P<end_date>[0-9, a-z, A-Z]+)/$', views.ExportSearchCustomerInvoice.as_view(), name='export_search_customer_invoice'),

    url(r'^list_invoice_detail/(?P<invoice_no>[0-9, a-z, A-Z]+)/$', views.ListInvoiceDetailView.as_view(), name='list_invoice_detail'),
    url(r'^list_client/$', views.ListClient.as_view(), name='list_client'),
    url(r'^owe_list/$', views.OweClient.as_view(), name='owe_list'),
    url(r'^compansate_remaining/(?P<invoice_no>[0-9, a-z, A-Z]+)/$', views.CompansateRemaining.as_view(), name='compansate_remaining'),
    url(r'^make_payment/$', views.MakePayment.as_view(), name='make_payment'),
    url(r'^owe_list_search/$', views.OweListSearch.as_view(), name='owe_list_search'),
    url(r'^save_list/$', views.SaveList.as_view(), name='save_list'),
    url(r'^delete_save/(?P<pk>[0-9]+)/$', views.DeleteSave.as_view(), name='delete_save'),
    url(r'^search_save_list/$', views.SearchSaveList.as_view(), name='search_save_list'),
    url(r'^save_payment/(?P<invoice_no>[0-9, a-z, A-Z]+)/$', views.PaymentSaveView.as_view(), name='save_payment'),
    url(r'^make_save_payment/$', views.MakeSavePayment.as_view(), name='make_save_payment'),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sell/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout


app_name = 'sell'
urlpatterns = [
    url(r'^$', views.SaleView.as_view(), name='sale_view'),
   	url(r'^filter_category/$', views.filter_category, name='filter_category'),
   	url(r'^filter_product/$', views.filter_product, name='filter_product'),
   	url(r'^filter_customer/$', views.filter_customer, name='filter_customer'),
   	url(r'^save_order_product_list/$', views.save_order_product_list, name='save_order_product_list'),
   	url(r'^check_invoice_product_list/$', views.check_invoice_product_list, name='check_invoice_product_list'),
   	url(r'^make_invoice_payment/$', views.make_invoice_payment, name='cancelSelling'),
   	url(r'^cancel_selling/$', views.cancel_selling, name='cancel_selling'),
    url(r'^update_order/$', views.update_order, name='update_order'),
    url(r'^delete_invoice/$', views.delete_invoice, name='delete_invoice'),
    url(r'^sub_make_invoice_payment/$', views.sub_make_invoice_payment, name='sub_make_invoice_payment'),
    url(r'^sub_make_payment/$', views.sub_make_payment, name='sub_make_payment'),
    url(r'^print_report/(?P<invoice_id>[0-9, a-z, A-Z]+)/$', views.print_report.as_view(), name='print_report'),
    url(r'^sell_history/$', views.SellHistoryView.as_view(), name='sell_history'),

   
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usercontrol/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.conf import settings 
from django.conf.urls.static import static 

from django.contrib.auth import views as auth_views


app_name = 'usercontrol'

urlpatterns = [
    url(r'^login/$', views.UserLoginView.as_view(), name='login'),
    url(r'^logout/$', views.auth_logout, name='auth_logout' ),
	url(r'^register/$', views.UserFormView.as_view(), name='register'),
	url(r'^usercontrol/', views.IndexView.as_view(), name='index'),
	url(r'^userlist/', views.ListUserView.as_view(), name='listuser'),

	url(r'^list_user_invoice/(?P<pk>[0-9, a-z, A-Z]+)/$', views.ListUserInvoice.as_view(), name='list_user_invoice'),

	url(r'^search_list_user_invoice/$', views.SearchListUserInvoice.as_view(), name='search_list_user_invoice'),
	url(r'^export_list_invoice/(?P<pk>[0-9, a-z, A-Z]+)/$', views.ExportListInvoiceView.as_view(), name='export_list_invoice'),

	url(r'^export_search_list_invoice/(?P<pk>[0-9, a-z, A-Z]+)/(?P<start_date>[0-9, a-z, A-Z]+)/(?P<end_date>[0-9, a-z, A-Z]+)/$', views.ExportSearchListInvoiceView.as_view(), name='export_search_list_invoice'),


	url(r'^all_user_invoice/$', views.AllUserInvoiceView.as_view(), name='all_user_invoice'),
	url(r'^search_all_user_invoice/$', views.SearchAllUserInvoiceView.as_view(), name='search_all_user_invoice'),
	url(r'^export_all_user_invoice/$', views.ExportAllUserInvoiceView.as_view(), name='export_all_user_invoice'),
	url(r'^export_all_search_user_invoice/(?P<key_term>[0-9, a-z, A-Z]+)/(?P<start_date>[0-9, a-z, A-Z]+)/(?P<end_date>[0-9, a-z, A-Z]+)/$', views.ExportAllSearchUserInvoiceView.as_view(), name='export_all_search_user_invoice'),


	# url(r'^login/$', auth_views.login, name='login'),	
	# url(r'^logout/$', views.auth_logout, name='auth_logout' ),
]

MainView/models.py
from django.db import models

# Create your models here.

MainView/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404
from django.http import HttpResponse
from django.template import loader 
from django.views import generic
from django.urls import reverse_lazy


from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout, login
from django.views.generic import View, TemplateView 
from product.models import Product, Promotion, ProductCategory
from customer.models import Customer

from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.template import loader 
from django.views.generic.list import ListView
from django.contrib import messages


class IndexView(SuccessMessageMixin, generic.ListView):
	template_name = 'MainView/default.html'
	context_object_name = 'all_product'
	paginate_by = 20

	@method_decorator(login_required(''))
	def dispatch(self, request, *args, **kwargs):	
		return super(self.__class__, self).dispatch(request, *args, **kwargs)
	
	def get_queryset(self):
		return Product.objects.filter(is_status=True).order_by('-created_at')

	def get(self, request):
		iuser = User.objects.count()
		icustomer = Customer.objects.count()
		iproduct = Product.objects.count()
		ipromotion = Promotion.objects.count()
		icategory = ProductCategory.objects.count()
		return render(request, self.template_name, { 'count_user': iuser, 'count_customer':icustomer, 'count_product_category': icategory, 'count_promotion':ipromotion })

# class DetailView(generic.DetailView):
# 	template_name =  'product/detail.html'

# 	def get(self, request, *args, **kwargs):
# 		print(self.kwargs['pk'])
		
# 		if self.kwargs['pk']:
# 			try:
# 				data = Product.objects.filter(id=self.kwargs['pk'], is_status=True)

# 				return render(request, self.template_name, {'products':data})
# 			except Product.DoesNotExist:
# 				raise Http404(" Data does not exist")
# 		else:
# 			raise Http404("Please check your data again.")


# class SearchProductView(View):
# 	template_name = 'product/search.html'
# 	form = ProductSearchForm

# 	def post(self, request):
# 		print('hello')
# 		q = request.GET['q']
		
# 		data = Product.objects.filter(name = q, is_status=True)

# 		return render(request, self.template_name, {'products':data})
	

MainView/templates/userprofile/all_user_invoice.html
{% extends 'product/base.html' %}

{% block title %} User invoices {% endblock %}

{% block body %}

	<div>
		<div class="home_title">
			<p> <span class="glyphicon glyphicon-th-large">  </span>  All invoices </p>
			<div class="search_bg_box" style="display: table;">
				<form class="form-inline" action="{% url 'usercontrol:search_all_user_invoice' %}" method="get" style="margin-top: 2px; ">
					{% csrf_token %}
					<div class="form-group">
				      <input style="margin-left: 0px; padding-left: 10px; min-width: 250px;" type="text" class="form-control" name= "q" value="" placeholder="Enter invoice ID" >		
				  	</div>
		    		<div class="form-group">
		    			<div class="input-group date form_date col-md-5" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
		                    <input class="form-control" size="16" type="datetime" value="" readonly style="min-width: 250px;" id="start_date" name = "start_date">
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
							<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
						<input type="hidden" id="dtp_input2" value="" /><br/>
		            </div>

		            <div class="form-group">
		                <div class="input-group date form_date col-md-5" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
		                    <input class="form-control" size="16" type="datetime" value="" readonly style="min-width: 250px;" id="end_date" name = "end_date">
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
							<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
						<input type="hidden" id="dtp_input2" value="" /><br/>
		            </div>
				  <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span> Seach</button>
				</form>
			</div>
		</div>
		
		<div class="row">
			<div class="col-md-12">
				<table class="table">
					<thead>
						<tr>
							<th>No</th>
							<th>Invoice</th>
							<th>Seller</th>
							<th>Total product</th>
							<th>Date</th>
							<th>Detail</th>

						</tr>
					</thead>
					<tbody>
						{% if all_invoices %}

							{% for i in all_invoices %}							
								<tr>
									<td>{{forloop.counter}}</td>
									<td> {{ i.invoice_number }}</td>
									<td> {{ i.user.first_name }} {{ i.user.last_name }} </td>

									{% if i.sale_invoice.all.count > 0 %}
										<td> {{ i.sale_invoice.all.count }} </td>
									{% else %}
										<td> 0 </td>
									{% endif %}
									<td> {{ i.created_at }} </td>
									<td> <a href="{% url 'customer:list_invoice_detail' i.invoice_number %}"> <span class="glyphicon glyphicon-hand-right"> Show </span> </a></td>
								</tr>
							{% endfor %}
						{% else %}
							<tr>
								<td colspan="6" style="text-align: center;"><h4 style="color:red;">No invoice today.</h4></td>
							</tr>
						{% endif %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

	{% if all_invoices %}
		<div style="margin-bottom: 20px; margin-top: 20px;">
			<a href = "{% url 'usercontrol:export_all_user_invoice' %}" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-print"></span> Export</a>
		</div>
	{% endif %}
	
	<div class="pagination_index">
		{% if all_data.count > paginator_num  %}
			<ul class="pagination" style="margin:0px 0px !important">
			{% if all_invoices.has_previous %}
			    <li>
			    	<span><a href="?page=1">&laquo; first</a></span>
			    </li>
			    <li>
			        <span><a href="?page={{ all_invoices.previous_page_number }}">Previous</a></span>
			    </li>
			{% endif %}
			    <li class="">
			        <span>Page {{ all_invoices.number }} of {{ all_invoices.paginator.num_pages }}.</span>
			    </li>
			{% if all_invoices.has_next %}
				<li><span><a href="?page={{ all_invoices.next_page_number }}">Next</a></span></li>
			    <li>
			        <span><a href="?page={{ all_invoices.paginator.num_pages }}">last &raquo;</a></span>
			    </li>
			{% endif %}
			</ul>
		{% endif %}
	</div>


	{% block javascript %}

		<script type="text/javascript">

			$('.form_datetime').datetimepicker({
		        //language:  'fr',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 2,
				forceParse: 0,
		        showMeridian: 1
		    });
			$('.form_date').datetimepicker({
		        language:  'fr',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 2,
				minView: 2,
				forceParse: 0
		    });
			$('.form_time').datetimepicker({
		        language:  'fr',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 1,
				minView: 0,
				maxView: 1,
				forceParse: 0
		    });
		</script>
	{% endblock %}


{% endblock %}

MainView/templates/userprofile/search_all_user_invoice.html
{% extends 'product/base.html' %}

{% block title %} User invoices {% endblock %}

{% block body %}

	<div>
		<div class="home_title">
			<p> <span class="glyphicon glyphicon-th-large">  </span>  Search result </p>
			
		</div>
		
		<div class="row">
			<div class="col-md-12">
				<table class="table">
					<thead>
						<tr>
							<th>No</th>
							<th>Invoice</th>
							<th>Seller</th>
							<th>Total product</th>
							<th>Date</th>
							<th>Detail</th>

						</tr>
					</thead>
					<tbody>
						{% if all_invoices %}

							{% for i in all_invoices %}							
								<tr>
									<td>{{forloop.counter}}</td>
									<td> {{ i.invoice_number }}</td>
									<td> {{ i.user.first_name }} {{ i.user.last_name }} </td>

									{% if i.sale_invoice.all.count > 0 %}
										<td> {{ i.sale_invoice.all.count }} </td>
									{% else %}
										<td> 0 </td>
									{% endif %}
									<td> {{ i.created_at }} </td>
									<td> <a href="{% url 'customer:list_invoice_detail' i.invoice_number %}"> <span class="glyphicon glyphicon-hand-right"> Show </span> </a></td>
								</tr>
							{% endfor %}
						{% else %}
							<tr>
								<td colspan="6" style="text-align: center;"><h4 style="color:red;">Search not found.</h4></td>
							</tr>
						{% endif %}
					</tbody>
				</table>
			</div>
		</div>
	</div>

	{% if all_invoices %}
		<div style="margin-bottom: 20px; margin-top: 20px;">
			<!-- <a href = "#" type="button" class="btn btn-primary">Preview</a> -->
			<a href = "{% url 'usercontrol:export_all_search_user_invoice' key_term start_date end_date %}" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-print"></span> Export</a>
		</div>
	{% endif %}
	
	<div class="pagination_index">
		{% if all_data.count > paginator_num  %}
			<ul class="pagination" style="margin:0px 0px !important">
			{% if all_invoices.has_previous %}
			    <li>
			    	<span><a href="?page=1">&laquo; first</a></span>
			    </li>
			    <li>
			        <span><a href="?page={{ all_invoices.previous_page_number }}">Previous</a></span>
			    </li>
			{% endif %}
			    <li class="">
			        <span>Page {{ all_invoices.number }} of {{ all_invoices.paginator.num_pages }}.</span>
			    </li>
			{% if all_invoices.has_next %}
				<li><span><a href="?page={{ all_invoices.next_page_number }}">Next</a></span></li>
			    <li>
			        <span><a href="?page={{ all_invoices.paginator.num_pages }}">last &raquo;</a></span>
			    </li>
			{% endif %}
			</ul>
		{% endif %}
	</div>


	{% block javascript %}

		<script type="text/javascript">

			$('.form_datetime').datetimepicker({
		        //language:  'fr',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 2,
				forceParse: 0,
		        showMeridian: 1
		    });
			$('.form_date').datetimepicker({
		        language:  'fr',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 2,
				minView: 2,
				forceParse: 0
		    });
			$('.form_time').datetimepicker({
		        language:  'fr',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 1,
				minView: 0,
				maxView: 1,
				forceParse: 0
		    });
		</script>
	{% endblock %}
{% endblock %}

MainView/templates/userprofile/user_invoice.html
{% extends 'product/base.html' %}

{% block title %} User invoices {% endblock %}

{% block body %}




	<div>
		<div class="home_title">
			<p> <span class="glyphicon glyphicon-th-large">  </span>  User's invoice </p>
			<div class="search_bg_box" style="display: table;">
				<form class="form-inline" action="{% url 'usercontrol:search_list_user_invoice' %}" method="get" style="margin-top: 2px; ">
					{% csrf_token %}

		    		<div class="form-group">
		    			<input type="hidden" value="{{ user_id }}" id="user_id" name="user_id">
		                <div class="input-group date form_date col-md-5" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
		                	

		                    <input class="form-control" size="16" type="datetime" value="" readonly style="min-width: 250px;" id="start_date" name = "start_date">
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
							<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
						<input type="hidden" id="dtp_input2" value="" /><br/>
		            </div>

		            <div class="form-group">
		                <div class="input-group date form_date col-md-5" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
		                    <input class="form-control" size="16" type="datetime" value="" readonly style="min-width: 250px;" id="end_date" name = "end_date">
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
							<span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
						<input type="hidden" id="dtp_input2" value="" /><br/>
		            </div>
				  <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span> Seach</button>
				</form>
			</div>
		</div>


		
		<div class="row">
			<div class="col-md-12">
				<table class="table">
					<thead>
						<tr>
							<th>No</th>
							<th>Invoice</th>
							<th>Seller</th>
							<th>Total product</th>
							<th>Date</th>
							<th>Detail</th>

						</tr>
					</thead>

					<tbody>
						{% if all_invoices %}
							{% for i in all_invoices %}							
								<tr>
									<td>{{forloop.counter}}</td>
									<td> {{ i.invoice_number }}</td>
									<td> {{ i.user.first_name }} {{ i.user.last_name }} </td>

									{% if i.sale_invoice.all.count > 0 %}
										<td> {{ i.sale_invoice.all.count }} </td>
									{% else %}
										<td> 0 </td>
									{% endif %}
									<td> {{ i.created_at }} </td>
									<td> <a href="{% url 'customer:list_invoice_detail' i.invoice_number %}"> <span class="glyphicon glyphicon-hand-right"> Show </span> </a></td>
								</tr>
							{% endfor %}
						{% else %}
							<tr>
								<td colspan="6" style="text-align: center;"><h4 style="color:red;">No invoice today.</h4></td>
							</tr>
						{% endif %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	{% if all_invoices %}

		<div style="margin-bottom: 20px; margin-top: 20px;">
			<!-- <a href = "#" type="button" class="btn btn-primary">Preview</a> -->
			<a href = "{% url 'usercontrol:export_list_invoice' user_id %}" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-print"></span> Export</a>
		</div>
	{% endif %}
	<div class="pagination_index">
	
		
		{% if all_data.count > paginator_num  %}
			<ul class="pagination" style="margin:0px 0px !important">
			{% if all_invoices.has_previous %}
			    <li>
			    	<span><a href="?page=1">&laquo; first</a></span>
			    </li>
			    <li>
			        <span><a href="?page={{ all_invoices.previous_page_number }}">Previous</a></span>
			    </li>
			{% endif %}
			    <li class="">
			        <span>Page {{ all_invoices.number }} of {{ all_invoices.paginator.num_pages }}.</span>
			    </li>
			{% if all_invoices.has_next %}
				<li><span><a href="?page={{ all_invoices.next_page_number }}">Next</a></span></li>
			    <li>
			        <span><a href="?page={{ all_invoices.paginator.num_pages }}">last &raquo;</a></span>
			    </li>
			{% endif %}
			</ul>

		{% endif %}
		
	</div>


	{% block javascript %}

		<script type="text/javascript">

			$('.form_datetime').datetimepicker({
		        //language:  'fr',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 2,
				forceParse: 0,
		        showMeridian: 1
		    });
			$('.form_date').datetimepicker({
		        language:  'fr',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 2,
				minView: 2,
				forceParse: 0
		    });
			$('.form_time').datetimepicker({
		        language:  'fr',
		        weekStart: 1,
		        todayBtn:  1,
				autoclose: 1,
				todayHighlight: 1,
				startView: 1,
				minView: 0,
				maxView: 1,
				forceParse: 0
		    });
		</script>
	{% endblock %}


{% endblock %}