MainView/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout


app_name = 'MainView'
urlpatterns = [
    url(r'', views.IndexView.as_view(), name='main_view_index'),  
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RTsite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path, include
from django.apps import apps
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout

"""
    Check data for uploading
"""
from django.conf import settings 
from django.conf.urls.static import static 

app_name = 'RTsite'
admin.site.site_header = "RTMK Admin"
admin.site.site_title = "RTMK Admin Portal"
admin.site.index_title = "Welcome to RTMK product marketing "

urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^admin/', include(admin.site.urls)),
    # path('category/', include('category.urls')),
    # path('', include('category.urls')), # login at the page loading. http://127.0.0.1:8000 #


    # path('product/', include('product.urls')),
    path('product_history/', include('product_history.urls')),
    path('usercontrol/', include('usercontrol.urls')),
    path('MainView/', include('MainView.urls')),
    path('customer/', include('customer.urls')),
    path('sell/', include('sell.urls')),
    path('', include('product.urls')),


    # path(
    #     'admin/password_reset/',
    #     auth_views.PasswordResetView.as_view(),
    #     name='admin_password_reset',
    # ),
    # path(
    #     'admin/password_reset/done/',
    #     auth_views.PasswordResetDoneView.as_view(),
    #     name='password_reset_done',
    # ),
    # path(
    #     'reset/<uidb64>/<token>/',
    #     auth_views.PasswordResetConfirmView.as_view(),
    #     name='password_reset_confirm',
    # ),
    # path(
    #     'reset/done/',
    #     auth_views.PasswordResetCompleteView.as_view(),
    #     name='password_reset_complete',
    # ),
    
    # url(r'^admin/', admin.site.urls),
    # url(r'^category/', views.index, 'category-index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout

app_name = 'customer'

urlpatterns = [
    path('', views.IndexView.as_view(), name='customer_index'),
    url(r'^detail/(?P<full_name>[0-9, a-z, A-Z]+)/$', views.CustomerDetailView.as_view(), name='customer_detail'),
    url(r'^export_customer_invoice/(?P<full_name>[0-9, a-z, A-Z]+)/$', views.ExportCustomerInvoiceView.as_view(), name='export_customer_invoice'),
    url(r'^search_customer_invoice/$', views.SearchCustomerInvoice.as_view(), name='search_customer_invoice'),
    url(r'^export_search_customer_invoice/(?P<full_name>[0-9, a-z, A-Z]+)/(?P<start_date>[0-9, a-z, A-Z]+)/(?P<end_date>[0-9, a-z, A-Z]+)/$', views.ExportSearchCustomerInvoice.as_view(), name='export_search_customer_invoice'),

    url(r'^list_invoice_detail/(?P<invoice_no>[0-9, a-z, A-Z]+)/$', views.ListInvoiceDetailView.as_view(), name='list_invoice_detail'),
    url(r'^list_client/$', views.ListClient.as_view(), name='list_client'),
    url(r'^owe_list/$', views.OweClient.as_view(), name='owe_list'),
    url(r'^compansate_remaining/(?P<invoice_no>[0-9, a-z, A-Z]+)/$', views.CompansateRemaining.as_view(), name='compansate_remaining'),
    url(r'^make_payment/$', views.MakePayment.as_view(), name='make_payment'),
    url(r'^owe_list_search/$', views.OweListSearch.as_view(), name='owe_list_search'),
    url(r'^save_list/$', views.SaveList.as_view(), name='save_list'),
    url(r'^delete_save/(?P<pk>[0-9]+)/$', views.DeleteSave.as_view(), name='delete_save'),
    url(r'^search_save_list/$', views.SearchSaveList.as_view(), name='search_save_list'),
    url(r'^save_payment/(?P<invoice_no>[0-9, a-z, A-Z]+)/$', views.PaymentSaveView.as_view(), name='save_payment'),
    url(r'^make_save_payment/$', views.MakeSavePayment.as_view(), name='make_save_payment'),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout


from .views import SearchProductView, RateView

app_name = 'product'

urlpatterns = [
    path('', views.IndexView.as_view(), name='product_index'),
    path('search/', SearchProductView.as_view(), name='product_search'),
    path('request_rate/', RateView.as_view(), name='request_rate'),
    # path('request_rate/', views.RateView, name='request_rate'),
  
  	url(r'^product_in_stock/', views.ProductInStockView.as_view(), name='product_in_stock'),
    url(r'^detail/(?P<pk>[0-9]+)/', views.DetailView.as_view(), name='product_detail'),
    url(r'^category_list/', views.CategoryListView.as_view(), name='category_list'),
    url(r'^category_product/(?P<pk>[0-9]+)/(?P<cate_name>[0-9, a-z, A-Z]+)/', views.CategoryProductView.as_view(), name='category_product'),
    url(r'^export_stock/$', views.ExportStock.as_view(), name='export_stock'),
    
    # url(r'^$', views.IndexView.as_view(), name='product_index'),
 
    # url(r'^request_rate/$', views.RateView.as_view(), name='request_rate'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sell/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout


app_name = 'sell'
urlpatterns = [
    url(r'^$', views.SaleView.as_view(), name='sale_view'),
   	url(r'^filter_category/$', views.filter_category, name='filter_category'),
   	url(r'^filter_product/$', views.filter_product, name='filter_product'),
   	url(r'^filter_customer/$', views.filter_customer, name='filter_customer'),
   	url(r'^save_order_product_list/$', views.save_order_product_list, name='save_order_product_list'),
   	url(r'^check_invoice_product_list/$', views.check_invoice_product_list, name='check_invoice_product_list'),
   	url(r'^make_invoice_payment/$', views.make_invoice_payment, name='cancelSelling'),
   	url(r'^cancel_selling/$', views.cancel_selling, name='cancel_selling'),
    url(r'^update_order/$', views.update_order, name='update_order'),
    url(r'^delete_invoice/$', views.delete_invoice, name='delete_invoice'),
    url(r'^sub_make_invoice_payment/$', views.sub_make_invoice_payment, name='sub_make_invoice_payment'),
    url(r'^sub_make_payment/$', views.sub_make_payment, name='sub_make_payment'),
    url(r'^print_report/(?P<invoice_id>[0-9, a-z, A-Z]+)/$', views.print_report.as_view(), name='print_report'),
    url(r'^sell_history/$', views.SellHistoryView.as_view(), name='sell_history'),

   
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usercontrol/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from django.conf import settings 
from django.conf.urls.static import static 

from django.contrib.auth import views as auth_views


app_name = 'usercontrol'

urlpatterns = [
    url(r'^login/$', views.UserLoginView.as_view(), name='login'),
    url(r'^logout/$', views.auth_logout, name='auth_logout' ),
	url(r'^register/$', views.UserFormView.as_view(), name='register'),
	url(r'^usercontrol/', views.IndexView.as_view(), name='index'),
	url(r'^userlist/', views.ListUserView.as_view(), name='listuser'),

	url(r'^list_user_invoice/(?P<pk>[0-9, a-z, A-Z]+)/$', views.ListUserInvoice.as_view(), name='list_user_invoice'),

	url(r'^search_list_user_invoice/$', views.SearchListUserInvoice.as_view(), name='search_list_user_invoice'),
	url(r'^export_list_invoice/(?P<pk>[0-9, a-z, A-Z]+)/$', views.ExportListInvoiceView.as_view(), name='export_list_invoice'),

	url(r'^export_search_list_invoice/(?P<pk>[0-9, a-z, A-Z]+)/(?P<start_date>[0-9, a-z, A-Z]+)/(?P<end_date>[0-9, a-z, A-Z]+)/$', views.ExportSearchListInvoiceView.as_view(), name='export_search_list_invoice'),


	url(r'^all_user_invoice/$', views.AllUserInvoiceView.as_view(), name='all_user_invoice'),
	url(r'^search_all_user_invoice/$', views.SearchAllUserInvoiceView.as_view(), name='search_all_user_invoice'),
	url(r'^export_all_user_invoice/$', views.ExportAllUserInvoiceView.as_view(), name='export_all_user_invoice'),
	url(r'^export_all_search_user_invoice/(?P<key_term>[0-9, a-z, A-Z]+)/(?P<start_date>[0-9, a-z, A-Z]+)/(?P<end_date>[0-9, a-z, A-Z]+)/$', views.ExportAllSearchUserInvoiceView.as_view(), name='export_all_search_user_invoice'),


	# url(r'^login/$', auth_views.login, name='login'),	
	# url(r'^logout/$', views.auth_logout, name='auth_logout' ),
]

MainView/models.py
from django.db import models

# Create your models here.

MainView/views.py
from django.shortcuts import render, redirect, get_object_or_404, Http404
from django.http import HttpResponse
from django.template import loader 
from django.views import generic
from django.urls import reverse_lazy


from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout, login
from django.views.generic import View, TemplateView 
from product.models import Product, Promotion, ProductCategory
from customer.models import Customer

from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.template import loader 
from django.views.generic.list import ListView
from django.contrib import messages


class IndexView(SuccessMessageMixin, generic.ListView):
	template_name = 'MainView/default.html'
	context_object_name = 'all_product'
	paginate_by = 20

	@method_decorator(login_required(''))
	def dispatch(self, request, *args, **kwargs):	
		return super(self.__class__, self).dispatch(request, *args, **kwargs)
	
	def get_queryset(self):
		return Product.objects.filter(is_status=True).order_by('-created_at')

	def get(self, request):
		iuser = User.objects.count()
		icustomer = Customer.objects.count()
		iproduct = Product.objects.count()
		ipromotion = Promotion.objects.count()
		icategory = ProductCategory.objects.count()
		return render(request, self.template_name, { 'count_user': iuser, 'count_customer':icustomer, 'count_product_category': icategory, 'count_promotion':ipromotion })

# class DetailView(generic.DetailView):
# 	template_name =  'product/detail.html'

# 	def get(self, request, *args, **kwargs):
# 		print(self.kwargs['pk'])
		
# 		if self.kwargs['pk']:
# 			try:
# 				data = Product.objects.filter(id=self.kwargs['pk'], is_status=True)

# 				return render(request, self.template_name, {'products':data})
# 			except Product.DoesNotExist:
# 				raise Http404(" Data does not exist")
# 		else:
# 			raise Http404("Please check your data again.")


# class SearchProductView(View):
# 	template_name = 'product/search.html'
# 	form = ProductSearchForm

# 	def post(self, request):
# 		print('hello')
# 		q = request.GET['q']
		
# 		data = Product.objects.filter(name = q, is_status=True)

# 		return render(request, self.template_name, {'products':data})
	

MainView/templates/MainView/default.html
{% extends 'product/base.html' %}

{% block title %} Dashboard {% endblock %}

{% block body %}

	<div>
		<div class="home_title">
			<p> <span class="glyphicon glyphicon-th-large">  </span> Dashboard </p>
		</div>
		<div class="home_menu">
			<div class="row" style="margin-top: 20px;">

				<!-- Block user -->
				<div class="col-xs-6 col-sm-4 col-md-3">
					<div class="home_box_user">
						<div class="home_user">
							
							<div class="default_item_left">
								<span class="glyphicon glyphicon-user default_item_left_icon" ></span>
							</div>
							<div class= "default_item_right">
								{% if count_user > 1 %}
									<p> {{ count_user }} </p>
									<p> Users </p>
								{% else %}
									<p> {{ count_user }} </p>
									<p> User </p>
								{% endif %}
							</div>

						</div>
						<div class="home_box_detail">
							<a href="{% url 'usercontrol:listuser' %}">
								<table style="width: 100%;">
									<tr>
										<td>View detail</td>
										<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
									</tr>
								</table>
							</a>
						</div>
					</div>
				</div>



				<!-- Block customer -->
				<div class="col-xs-6 col-sm-4 col-md-3 ">
					<div class="home_box_customer">
						<div class="home_customer">
							<div class="default_item_left">
								<span class="glyphicon glyphicon-header default_item_left_icon" ></span>
							</div>
							<div class= "default_item_right">
								{% if count_customer > 1 %}
									<p> {{ count_customer }} </p>
									<p> Customers </p>
								{% else %}
									<p> {{ count_customer }} </p>
									<p> Customer </p>
								{% endif %}
							</div>
						</div>



						<div class="home_box_detail">

							{% if count_customer > 0 %}
								<a href="{% url 'customer:customer_index' %}">
									<table style="width: 100%;">
										<tr>
											<td>View detail</td>
											<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
										</tr>
									</table>
								</a>
							{% else %}
								<a href="#">
									<table style="width: 100%;">
										<tr>
											<td>View detail</td>
											<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
										</tr>
									</table>
								</a>
							{% endif %}



						</div>
					</div>
				</div>

				
				<!-- Block category -->
				
				<div class="col-xs-6 col-sm-4 col-md-3">
					<div class="home_box_category">
						<div class="home_category">
							
							<div class="default_item_left">
								<span class="glyphicon glyphicon-list default_item_left_icon" ></span>
							</div>

							<div class= "default_item_right">
								{% if count_product_category > 1 %}
									<p> {{ count_product_category }} </p>
									<p> Categories </p>
								{% else %}
									<p> {{ count_product_category }} </p>
									<p> Category </p>
								{% endif %}
							</div>


						</div>
						<div class="home_box_detail">
							
							{% if count_product_category > 0 %}
								<a href="{% url 'product:category_list' %}">
									<table style="width: 100%;">
										<tr>
											<td>View detail</td>
											<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
										</tr>
									</table>
								</a>
							{% else %}
								<a href="#">
									<table style="width: 100%;">
										<tr>
											<td>View detail</td>
											<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
										</tr>
									</table>
								</a>
							{% endif %}

						</div>
					</div>
				</div>



				<!-- Block promotion -->
				<!-- <div class="col-xs-6 col-sm-4 col-md-3">
					<div class="home_box_promotion">
						<div class="home_promotion">
							<div class="default_item_left">
								<span class="glyphicon glyphicon-user default_item_left_icon" ></span>
							</div>
							<div class= "default_item_right">
								{% if count_promotion > 1 %}
									<p> {{ count_promotion }} </p>
									<p> Promotions </p>
								{% else %}
									<p> {{ count_promotion }} </p>
									<p> Promotion </p>
								{% endif %}
							</div>
						</div>
						<div class="home_box_detail">
							<a href="#">
								<table style="width: 100%;">
									<tr>
										<td>View detail</td>
										<td style="float:right;"><span class="glyphicon glyphicon-chevron-right"></span></td>
									</tr>
								</table>
							</a>
						</div>
					</div>
				</div> -->





			</div>
		</div>
	</div>

{% endblock %}